# Generated by Django 4.1.5 on 2023-04-14 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('category', models.CharField(choices=[('PM', 'Prescrided')], max_length=2)),
                ('product_image', models.ImageField(upload_to='prescribedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Prescribed_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prescribed_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=50)),
                ('product', models.ForeignKey(limit_choices_to={'category': 'NA'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
