# Generated by Django 4.1.5 on 2023-04-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_orders_amountpaid_remove_orders_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribed_medicine',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product'),
        ),
    ]
