# Generated by Django 4.1.5 on 2023-04-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_alter_prescribed_medicine_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescribedproduct',
            old_name='category',
            new_name='category_prescribed',
        ),
    ]
