# Generated by Django 4.1.5 on 2023-04-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_rename_category_prescribedproduct_category_prescribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribed_medicine',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.prescribedproduct'),
        ),
    ]
